name       : libva-intel-driver
version    : 1.8.1
release    : 4
source     :
    - https://freedesktop.org/software/vaapi/releases/libva-intel-driver/intel-vaapi-driver-1.8.1.tar.bz2 : efd041602635ce9450fbdf864563d3b95341ef3877337772af708d9cc17b2fce
license    : MIT
component  : xorg.display
summary    : Intel HD graphics VA-API implementation
description: |
    Intel HD graphics VA-API implementation
builddeps  :
    - pkgconfig(libva)
    - pkgconfig(libva-drm)
    - pkgconfig(libva-x11)
    - pkgconfig(egl)
    - pkgconfig(wayland-client)
    - pkgconfig(libva-wayland)
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
