name       : libva-intel-driver
version    : 2.2.0
release    : 7
source     :
    - https://github.com/intel/intel-vaapi-driver/releases/download/2.2.0/intel-vaapi-driver-2.2.0.tar.bz2 : e8a5f54694eb76aad42653b591030b8a53b1513144c09a80defb3d8d8c875c18
license    : MIT
component  : xorg.display
summary    : Intel HD graphics VA-API implementation
description: |
    Intel HD graphics VA-API implementation
builddeps  :
    - pkgconfig(intel-gen4asm)
    - pkgconfig(libdrm)
    - pkgconfig(libva)
    - pkgconfig(wayland-client)
    - pkgconfig(x11)
setup      : |
    %configure --enable-tests
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
