name       : libva-intel-driver
version    : 1.7.3
release    : 3
source     :
    - https://freedesktop.org/software/vaapi/releases/libva-intel-driver/libva-intel-driver-1.7.3.tar.bz2 : 76ad37d9fd5ae23d8ce6052d50b5e6438a8df9e769b13fe34b771cd453f4f937
license    : MIT
component  : xorg.display
summary    : Intel HD graphics VA-API implementation
description: |
    Intel HD graphics VA-API implementation
builddeps  :
    - pkgconfig(libva)
    - pkgconfig(libva-drm)
    - pkgconfig(libva-x11)
    - pkgconfig(egl)
    - pkgconfig(wayland-client)
    - pkgconfig(libva-wayland)
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
