name       : libva-intel-driver
version    : 2.1.0
release    : 6
source     :
    - https://github.com/intel/intel-vaapi-driver/releases/download/2.1.0/intel-vaapi-driver-2.1.0.tar.bz2 : ecfaf2ccc4b9af7340e002d2ef807d1e33051d4992f1983f5f4d60e516f86bdf
license    : MIT
component  : xorg.display
summary    : Intel HD graphics VA-API implementation
description: |
    Intel HD graphics VA-API implementation
builddeps  :
    - pkgconfig(libdrm)
    - pkgconfig(libva)
    - pkgconfig(wayland-client)
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
