name       : libva-intel-driver
version    : 2.0.0
release    : 5
source     :
    - https://github.com/01org/intel-vaapi-driver/releases/download/2.0.0/intel-vaapi-driver-2.0.0.tar.bz2 : 10f6b0a91f34715d8d4d9a9e0fb3cc0afe5fcf85355db1272bd5fff31522f469
license    : MIT
component  : xorg.display
summary    : Intel HD graphics VA-API implementation
description: |
    Intel HD graphics VA-API implementation
builddeps  :
    - pkgconfig(libdrm)
    - pkgconfig(libva)
    - pkgconfig(wayland-client)
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
