name       : libva-intel-driver
version    : 2.4.1
release    : 13
source     :
    - https://github.com/intel/intel-vaapi-driver/releases/download/2.4.1/intel-vaapi-driver-2.4.1.tar.bz2 : 0081fce08eb3a83f7d99c3b853c8fdfa0af437b8f5b0fb7c66faeb83bcbe0c19
license    : MIT
component  : xorg.display
summary    : Intel HD graphics VA-API implementation
description: |
    Intel HD graphics VA-API implementation
builddeps  :
    - pkgconfig(intel-gen4asm)
    - pkgconfig(libdrm)
    - pkgconfig(libva)
    - pkgconfig(wayland-client)
    - pkgconfig(x11)
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
# Tests can be validated locally, but not on build server
#check      : |
#    %make check
