name       : libva-intel-driver
version    : 2.3.0
release    : 10
source     :
    - https://github.com/intel/intel-vaapi-driver/archive/2.3.0.tar.gz : fcc3f09291e58fd316fd015d4e1329e7e03c38cffa4651bda725d500a66aa74e
license    : MIT
component  : xorg.display
summary    : Intel HD graphics VA-API implementation
description: |
    Intel HD graphics VA-API implementation
builddeps  :
    - pkgconfig(intel-gen4asm)
    - pkgconfig(libdrm)
    - pkgconfig(libva)
    - pkgconfig(wayland-client)
    - pkgconfig(x11)
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
# Tests can be validated locally, but not on build server
#check      : |
#    %make check
